### ISSUE TITLE
Dirichlet Boundary Condition Bug

### ISSUE THREAD

**Issue by VaSca92** [udcm-su/heat-diffusion-1D#10]
Dirichlet Boundary condition do not work properly:

Right boundary condition seems to be fixed at zero and also the numerical  value of the left boundary condition is not correct when the conductivity is not unitary

A bug fix is needed

**Comment by luksen99** [comment]
The problem is fixed. There was an issue with the computation of the flux in the main loop. Now we are treating the right-hand side boundary correctly and distinguish between Neumann and Dirichlet type correctly.
