### ISSUE TITLE
How to cite / acknowledge

### ISSUE THREAD

**Issue by lapofran** [udcm-su/heat-diffusion-1D#12]
Please indicate the preferred way to cite or acknowledge the use of this code. Thanks!

**Comment by luksen99** [comment]
Most likely we will do a DOI which can be cited. We will keep you updated.

**Comment by udcm** [comment]
You can now cite via DOI. It is in the README.

**Comment by udcm** [comment]
You can now cite via DOI!

**Comment by luksen99** [comment]
You can now cite via DOI

**Comment by luksen99** [comment]
You can now download the package via `pip install NTMpy` 
Also there is a second release which you can again cite via DOI.
