### ISSUE TITLE
Metal layer on dielectric

### ISSUE THREAD

**Issue by lapofran** [udcm-su/heat-diffusion-1D#13]
Hi, I would like to know whether there is a straightforward way to simulate a multilayer system where a metal thin film (e.g. gold) would be deposited on a dielectric (e.g. glass, quartz). The dynamics of the metal layer are easy solved as a single layer, two-temperature case, but in my understanding, the two-temperature model is not relevant to a large-gap dielectric.

**Comment by luksen99** [comment]
Hi, there is a straight forward way to do it: Create a TMM source with Air|Gold|Quartz|Air, that provides the complex refractive index of every layer, the refractive index of Quartz is real, so no light will be deposited if you heat your material. However, there will be a diffusion process of the heat from Gold -> Quartz.
With ´addLayer(length,heat_Conductivity,heat_Capacity, density,coupling_Constant)´ you can add the layers and then start the simulation.

**Comment by luksen99** [comment]
Note, the TTM mainly takes thermodynamical parameters into consideration. band gap and optical parameters are considered only through the refractive index of every layer. The main focus lies on how much of the light is absorbed in every layer. The rest is relaxation between the systems and diffusion into the material.

**Comment by luksen99** [comment]
A reference on |Gold|Glass| thin film measurements 

> Femtosecond pump–probe nondestructive examination of materials

**Comment by lapofran** [comment]
> 
> 
> Hi, there is a straight forward way to do it: Create a TMM source with Air|Gold|Quartz|Air, that provides the complex refractive index of every layer, the refractive index of Quartz is real, so no light will be deposited if you heat your material. However, there will be a diffusion process of the heat from Gold -> Quartz.
> With ´addLayer(length,heat_Conductivity,heat_Capacity, density,coupling_Constant)´ you can add the layers and then start the simulation.

Thanks for your quick answer. I see how using a transfer matrix in this multilayer case can be useful to compute the energy deposited. If I would define a simulation with 2 temperatures and then add a metal and dielectric layer, I would still be faced with the problem that I have to provide values for the electron thermal conductivity, electron heat conductivity and electron-phonon coupling of the dielectric layer, which are not readily available or defined for dielectrics: 
```python
sim = simulation(2, s)
#add layers (Length [m], conductivity [W / cm . K], heatCapacity [J / (m^3 . K^2)], density [kg / m^3], coupling [W/(m^3.K)])
sim.addLayer(200e-9, [317, 1], [lambda Te: 3.6e-3*Te, 129], 19300, 2.2e16) # Au Layer
sim.addLayer(4e-3, [???, 12], [???, 730], 2648, ???) # Quartz layer
```

With this simulation, I am seeking to get some insight on the evolution of the temperature with respect to depth in the dielectric layer upon excitation of the metal layer.

**Comment by luksen99** [comment]
Finding the physically right input for those parameters is a current topic of research and also one reason why we are interested in this software. Not only to verify results, once parameters are known, but also to test different parameters on this model and check with experimental results.

**Comment by lapofran** [comment]
Thank you for the reference. I was thinking that maybe a working approach could be to compute the dynamics in the metal layer with a two-temperature model, but to fall back to a single-temperature model in the case of the dielectric.

**Comment by luksen99** [comment]
That would be an excellent idea in principle but can not be easily realized with the current code. You could try to set the coupling constant of the second layer to 0, i.e. the two systems in the second layer will evolve individually. 
One more thing considering the heat capacity: One approach can be to go to Nist webbook and look for the total heat capacity of Quarz, then subtract the lattice contribution. This should give you a good approximation to the electron heat capacity of Quarz.
