### ISSUE TITLE
Spell out units for addLayer

### ISSUE THREAD

**Issue by lapofran** [udcm-su/heat-diffusion-1D#9]
Many thanks for publishing your code on GitHub! It looks useful and promising. 

I tried the example and it runs just fine, but when I wanted to modify the program, it was unclear which units I should use in the addLayer method, specifically for the heat capacity, density and coupling parameters. I would like to ask to spell out the units explicitly in the doc string.

Thanks, and best regards,
François

**Comment by luksen99** [comment]
Hey, thank you for your feedback! 
The units, in SI, of heat capacity is J/(m^3K^2).
Sometimes, it depends on the formulation of the diffusion equation, the heat capacity, C, is given as C/rho, that is heat capacity over density. 
The unit, in SI, of the coupling G is W/(m^3K)
I added a doc string to the function, print(sim.addLayer.__doc__), and I am going to update all the functions with short documentation in the future.
